<?php

$accountFields = [
    [
        'name' => 'cedula',
        'display' => 'Cédula',
        'placeholder' => '',
        'id' => 'cedula',
        'type' => 'integer',
        'size' => 5,
        'max' => 10,
        'min' => 7,
        'required' => true,
        'suspicious' => true,
        'value' => $edit ? $target_account['cedula'] : ''
    ],
    [
        'name' => 'names',
        'display' => 'Nombres',
        'placeholder' => 'Ambos nombres',
        'id' => 'names',
        'type' => 'text',
        'size' => 8,
        'min' => 5,
        'max' => 100,
        'required' => true,
        'suspicious' => true,
        'value' => $edit ? $target_account['names'] : '',
    ],
    [
        'name' => 'surnames',
        'display' => 'Apellidos',
        'placeholder' => 'Ambos apellidos',
        'id' => 'surnames',
        'type' => 'text',
        'size' => 8,
        'min' => 5,
        'max' => 100,
        'required' => true,
        'suspicious' => true,
        'value' => $edit ? $target_account['surnames'] : '',
    ],
    [
        'name' => 'phone',
        'display' => 'Teléfono',
        'placeholder' => 'Teléfono',
        'id' => 'phone',
        'type' => 'text',
        'size' => 8,
        'min' => 11,
        'max' => 11,
        'required' => true,
        'suspicious' => true,
        'value' => $edit ? $target_account['phone'] : '',
    ],
    [
        'name' => 'address',
        'display' => 'Dirección',
        'placeholder' => 'Dirección del cliente',
        'id' => 'address',
        'type' => 'textarea',
        'size' => 8,
        'required' => true,
        'suspicious' => false,
        'value' => $edit ? $target_account['address'] : '',
    ],
    [
        'name' => 'is_student',
        'display' => 'Es estudiante',
        'placeholder' => '',
        'id' => 'is_student',
        'type' => 'checkbox',
        'size' => 5,
        'required' => false,
        'suspicious' => true,
        'value' => $edit ? [$target_account['is_student']] : ['0'],
        'elements' => [['display' => 'Es estudiante', 'value' => '1']],
    ],
    [
        'name' => 'scholarship',
        'display' => 'Beca',
        'placeholder' => '',
        'id' => 'scholarship',
        'type' => 'select',
        'size' => 6,
        'required' => false,
        'suspicious' => true,
        'value' => $edit ? $target_account['scholarship_id'] : '',
        'elements' => $display_scholarships ?? [],
    ],
    [
        'name' => 'scholarship_coverage',
        'display' => '% Cobertura de la beca',
        'placeholder' => 'Ejemplo, 30, 50, 100',
        'id' => 'scholarship_coverage',
        'type' => 'integer',
        'size' => 6,
        'required' => false,
        'suspicious' => true,
        'value' => $edit ? ($target_account['scholarship_coverage'] === NULL ? '0' : $target_account['scholarship_coverage'] ) : '0',
    ],
    [
        'name' => 'company',
        'display' => 'Empresa',
        'placeholder' => '',
        'id' => 'company',
        'type' => 'select',
        'size' => 8,
        'required' => false,
        'suspicious' => true,
        'value' => $edit ? $target_account['company_id'] : '',
        'elements' => $display_companies ?? []
    ],
];

if($edit){
    $id_field = [
        'name' => 'id',
        'value' => $target_account['id']
    ];
    array_push($accountFields, $id_field);
}