<?php

$coinPriceFields = [
    [
        'name' => 'coin',
        'display' => 'Moneda',
        'placeholder' => '',
        'id' => 'coin',
        'type' => 'select',
        'size' => 4,
        'max' => 11,
        'min' => 1,
        'required' => true,
        'suspicious' => true,
        'value' => $target_coin['id'] ?? '',
        'elements' => $form ? $display_coins : '',
    ],
    [
        'name' => 'price',
        'display' => 'Tasa',
        'placeholder' => '',
        'id' => 'price',
        'type' => 'decimal',
        'size' => 4,
        'required' => true,
        'suspicious' => true,
        'value' => '0',
    ],
    [
        'name' => 'date',
        'display' => 'Fecha',
        'placeholder' => '',
        'id' => 'date',
        'type' => 'date',
        'size' => 4,
        'required' => true,
        'suspicious' => false,
        'value' => date('Y-m-d'),
        'max' => date('Y-m-d'),
    ],
];